import { useEffect, useRef, useState } from 'react'

/* KaTeX rendering, loaded on demand.

   KaTeX plus its fonts is larger than the whole current app bundle, and most
   conversations contain no math at all, so it is behind a dynamic import: the
   chunk is fetched from the local server the first time a formula appears and
   is shared by every formula after it. Until it resolves the TeX source is
   shown as-is, which is exactly what the reader saw before this existed.

   STRUCTURE, and it is load-bearing: katex.render() REPLACES the children of
   the node it is given. React must therefore never render children into that
   node -- if it does, the next reconcile tries to remove text nodes KaTeX
   already destroyed and throws NotFoundError, which unmounts the whole app.
   The source placeholder and the KaTeX host are siblings for that reason, and
   the host is empty in JSX and stays that way. During streaming `tex` changes
   on almost every frame, so this is not a rare path.

   Safety: the HTML KaTeX produces is generated by KaTeX FROM a TeX string --
   it is not model-authored markup being passed through. `trust: false` (the
   default) refuses \href, \url, \includegraphics and friends, and
   `throwOnError: false` renders an invalid formula as visibly-wrong TeX
   instead of throwing away the message around it. There is still no path by
   which raw HTML in model output reaches the DOM. */

let katexModule = null
let katexLoad = null

function loadKatex() {
  if (katexModule) return Promise.resolve(katexModule)
  if (!katexLoad) {
    katexLoad = Promise.all([
      import('katex'),
      import('katex/dist/katex.min.css'),
    ])
      .then(([module]) => {
        katexModule = module.default || module
        return katexModule
      })
      .catch((error) => {
        // Reset so a later formula can retry a load that failed transiently.
        katexLoad = null
        throw error
      })
  }
  return katexLoad
}

export function MathSpan({ tex, display = false }) {
  const hostRef = useRef(null)
  const [state, setState] = useState('pending')

  useEffect(() => {
    let cancelled = false
    setState('pending')
    loadKatex()
      .then((katex) => {
        if (cancelled || !hostRef.current) return
        katex.render(tex, hostRef.current, {
          displayMode: display,
          throwOnError: false,
          trust: false,
          strict: false,
          output: 'htmlAndMathml',
        })
        if (!cancelled) setState('ready')
      })
      .catch(() => {
        if (!cancelled) setState('failed')
      })
    return () => {
      cancelled = true
      // Leaving stale typeset output behind would show the previous formula
      // under the new source while the next render is in flight.
      if (hostRef.current) hostRef.current.textContent = ''
    }
  }, [tex, display])

  const Wrapper = display ? 'div' : 'span'
  const className = [
    'cx-math',
    display ? 'cx-math--display' : '',
    state === 'failed' ? 'cx-math--unrendered' : '',
  ].filter(Boolean).join(' ')

  return (
    <Wrapper
      className={className}
      data-math-state={state}
      title={state === 'failed' ? 'Math rendering is unavailable; showing the source' : undefined}
    >
      {/* Shown until KaTeX has typeset, and permanently if it never loads. */}
      {state !== 'ready' && <Wrapper className="cx-math__source">{tex}</Wrapper>}
      {/* Owned by KaTeX, never by React: no children here, ever. */}
      <Wrapper className="cx-math__host" ref={hostRef} />
    </Wrapper>
  )
}

export default MathSpan
