import { useEffect, useRef, useState } from 'react'

import { copyText } from '../../../lib/clipboard.js'

/* Mermaid rendering for ```mermaid fences, loaded on demand.

   Mermaid is by far the largest thing this app can pull in, and a
   conversation that never draws a diagram must not pay for it, so it sits
   behind a dynamic import like KaTeX. Everything before the chunk resolves --
   and everything after a failed parse -- is the ordinary code card the fence
   rendered before this existed, so a broken diagram never costs the reader the
   text of it.

   securityLevel 'strict' is Mermaid's own sanitizer: it strips script and
   event handlers from the SVG it generates, and disables click-bound
   JavaScript in diagram syntax. The SVG is generated by Mermaid from the
   diagram source; model-authored HTML still has no path to the DOM. */

let mermaidModule = null
let mermaidLoad = null
let initializedTheme = null

function currentTheme() {
  if (typeof document === 'undefined') return 'default'
  const explicit = document.documentElement.getAttribute('data-theme')
  if (explicit === 'dark') return 'dark'
  if (explicit === 'light') return 'default'
  const prefersDark = typeof window !== 'undefined'
    && typeof window.matchMedia === 'function'
    && window.matchMedia('(prefers-color-scheme: dark)').matches
  return prefersDark ? 'dark' : 'default'
}

function loadMermaid() {
  if (!mermaidLoad) {
    mermaidLoad = import('mermaid')
      .then((module) => {
        mermaidModule = module.default || module
        return mermaidModule
      })
      .catch((error) => {
        mermaidLoad = null
        throw error
      })
  }
  return mermaidLoad
}

async function renderDiagram(source, id) {
  const mermaid = await loadMermaid()
  const theme = currentTheme()
  /* initialize() is global and cheap; re-run it only when the theme actually
     changed, so a thread full of diagrams does not re-configure per render. */
  if (initializedTheme !== theme) {
    mermaid.initialize({ startOnLoad: false, securityLevel: 'strict', theme })
    initializedTheme = theme
  }
  const { svg } = await mermaid.render(id, source)
  return svg
}

let diagramSeq = 0

export function MermaidDiagram({ source, fallback }) {
  const hostRef = useRef(null)
  const [state, setState] = useState('pending')
  const [showSource, setShowSource] = useState(false)
  const [copied, setCopied] = useState(false)
  const copiedResetRef = useRef(null)
  const [themeTick, setThemeTick] = useState(0)

  /* Re-render on a theme change: the SVG bakes its colors in, so a diagram
     drawn in light mode stays light-on-light after the user switches. */
  useEffect(() => {
    if (typeof window === 'undefined') return undefined
    const observer = typeof MutationObserver === 'function'
      ? new MutationObserver(() => setThemeTick((tick) => tick + 1))
      : null
    observer?.observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme'] })
    const media = typeof window.matchMedia === 'function'
      ? window.matchMedia('(prefers-color-scheme: dark)')
      : null
    const onMedia = () => setThemeTick((tick) => tick + 1)
    media?.addEventListener?.('change', onMedia)
    return () => {
      observer?.disconnect()
      media?.removeEventListener?.('change', onMedia)
    }
  }, [])

  useEffect(() => {
    let cancelled = false
    diagramSeq += 1
    const id = `cx-mermaid-${diagramSeq}`
    setState('pending')
    renderDiagram(source, id)
      .then((svg) => {
        if (cancelled) return
        if (hostRef.current) hostRef.current.innerHTML = svg
        setState('ready')
      })
      .catch(() => {
        if (cancelled) return
        /* Mermaid appends a detached error node to <body> on a parse failure;
           remove it so a malformed diagram cannot leave debris on the page. */
        document.getElementById(`d${id}`)?.remove()
        setState('failed')
      })
    return () => { cancelled = true }
  }, [source, themeTick])

  useEffect(() => () => {
    if (copiedResetRef.current) window.clearTimeout(copiedResetRef.current)
  }, [])

  if (state === 'failed') return fallback

  const handleCopy = async () => {
    if (!(await copyText(source))) return
    setCopied(true)
    if (copiedResetRef.current) window.clearTimeout(copiedResetRef.current)
    copiedResetRef.current = window.setTimeout(() => setCopied(false), 1600)
  }

  return (
    <figure className="cx-mermaid" data-mermaid-state={state}>
      <figcaption className="cx-mermaid__bar">
        <span className="cx-mermaid__label">Diagram</span>
        <button type="button" onClick={() => setShowSource((value) => !value)}>
          {showSource ? 'Hide source' : 'Source'}
        </button>
        <button type="button" onClick={handleCopy} aria-label="Copy diagram source">
          {copied ? 'Copied' : 'Copy'}
        </button>
      </figcaption>
      {/* The source is the placeholder, exactly as the TeX source is for a
          formula: it is what shows while the chunk loads, so a diagram can
          never cost the reader the text of it.

          The placeholder and the SVG host are SIBLINGS, and the host has no
          children in JSX. Writing innerHTML into a node React also renders
          into makes the next reconcile try to remove children that are already
          gone, which throws NotFoundError and unmounts the whole app. */}
      <div className="cx-mermaid__canvas">
        {state === 'pending' && <pre className="cx-mermaid__pending">{source}</pre>}
        <div className="cx-mermaid__svg" ref={hostRef} role="img" aria-label="Mermaid diagram" />
      </div>
      {showSource && <pre className="cx-mermaid__source"><code>{source}</code></pre>}
    </figure>
  )
}

export default MermaidDiagram
