/* Curated set of models Camelid supports for local chat (exact rows it knows how
   to download + run). Catalog ids/repos/filenames/sizes match the backend catalog
   the install endpoint expects, so installCatalogModel(item) and the localStorage
   download-progress tracking (keyed by catalog_id) work directly. */
export const BONSAI_27B_VISION_PROJECTOR = Object.freeze({
  role: 'vision_projector',
  repo_id: 'prism-ml/Ternary-Bonsai-27B-gguf',
  filename: 'Ternary-Bonsai-27B-mmproj-Q8_0.gguf',
  size_bytes: 629246880,
})

export const SUPPORTED_MODELS = [
  {
    catalog_id: 'llama32_3b_instruct_q8_0',
    name: 'Llama 3.2 3B Instruct',
    repo_id: 'unsloth/Llama-3.2-3B-Instruct-GGUF',
    filename: 'Llama-3.2-3B-Instruct-Q8_0.gguf',
    size_bytes: 3422709216,
    quant: 'Q8_0',
    blurb: 'Good at everyday chat, summarizing, and writing — a solid all-rounder.',
    recommended: true,
  },
  {
    catalog_id: 'llama32_1b_instruct_q8_0',
    name: 'Llama 3.2 1B Instruct',
    repo_id: 'unsloth/Llama-3.2-1B-Instruct-GGUF',
    filename: 'Llama-3.2-1B-Instruct-Q8_0.gguf',
    size_bytes: 1346203104,
    quant: 'Q8_0',
    blurb: 'A small, fast model for quick chat and simple tasks.',
  },
  {
    catalog_id: 'llama3_2_1b_instruct_iq4_xs',
    name: 'Llama 3.2 1B Instruct (IQ4_XS)',
    repo_id: 'bartowski/Llama-3.2-1B-Instruct-GGUF',
    filename: 'Llama-3.2-1B-Instruct-IQ4_XS.gguf',
    size_bytes: 743141504,
    quant: 'IQ4_XS',
    blurb: 'The same small model at under half the size — quickest to download.',
  },
  {
    /* The certified 3B K-quants are bartowski's exact uploads. Unsloth ships
       same-named files at different sizes, so repo_id is evidence here, not a
       preference — see the matching note in curated_catalog() (src/api/mod.rs). */
    catalog_id: 'llama_3_2_3b_instruct_q4_k_m',
    name: 'Llama 3.2 3B Instruct (Q4_K_M)',
    repo_id: 'bartowski/Llama-3.2-3B-Instruct-GGUF',
    filename: 'Llama-3.2-3B-Instruct-Q4_K_M.gguf',
    size_bytes: 2019377696,
    quant: 'Q4_K_M',
    blurb: 'The all-rounder at about half the size, with a small quality tradeoff.',
  },
  {
    catalog_id: 'llama_3_2_3b_instruct_q5_k_m',
    name: 'Llama 3.2 3B Instruct (Q5_K_M)',
    repo_id: 'bartowski/Llama-3.2-3B-Instruct-GGUF',
    filename: 'Llama-3.2-3B-Instruct-Q5_K_M.gguf',
    size_bytes: 2322154016,
    quant: 'Q5_K_M',
    blurb: 'A middle ground between the Q4_K_M download and the full-size Q8_0.',
  },
  {
    catalog_id: 'tinyllama_1_1b_chat_q8_0',
    name: 'TinyLlama 1.1B Chat',
    repo_id: 'TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF',
    filename: 'tinyllama-1.1b-chat-v1.0.Q8_0.gguf',
    size_bytes: 1169007424,
    quant: 'Q8_0',
    blurb: 'A tiny chat model for basic conversation and quick experiments.',
  },
  {
    catalog_id: 'llama3_8b_instruct_q8_0',
    name: 'Llama 3 8B Instruct',
    repo_id: 'MaziyarPanahi/Meta-Llama-3-8B-Instruct-GGUF',
    filename: 'Meta-Llama-3-8B-Instruct.Q8_0.gguf',
    size_bytes: 8540846592,
    quant: 'Q8_0',
    blurb: 'Higher-quality chat, reasoning, and longer-form writing.',
  },
  {
    catalog_id: 'mistral_7b_instruct_v0_3_q8_0',
    name: 'Mistral 7B Instruct v0.3',
    repo_id: 'bartowski/Mistral-7B-Instruct-v0.3-GGUF',
    filename: 'Mistral-7B-Instruct-v0.3-Q8_0.gguf',
    size_bytes: 7702565088,
    quant: 'Q8_0',
    blurb: 'Strong at reasoning, coding, and following detailed instructions.',
  },
  {
    catalog_id: 'lfm2_5_2_6b_q8_0',
    name: 'LFM2.5 2.6B',
    repo_id: 'LiquidAI/LFM2.5-2.6B-GGUF',
    filename: 'LFM2.5-2.6B-Q8_0.gguf',
    size_bytes: 2874779456,
    quant: 'Q8_0',
    blurb: 'A compact hybrid chat model with a fast local runnable lane.',
  },
  {
    catalog_id: 'qwen3_0_6b_instruct_q8_0',
    name: 'Qwen3 0.6B',
    repo_id: 'Qwen/Qwen3-0.6B-GGUF',
    filename: 'Qwen3-0.6B-Q8_0.gguf',
    size_bytes: 639446688,
    quant: 'Q8_0',
    blurb: 'A compact multilingual model for quick chat and light reasoning.',
  },
  {
    catalog_id: 'qwen3_1_7b_instruct_q8_0',
    name: 'Qwen3 1.7B',
    repo_id: 'Qwen/Qwen3-1.7B-GGUF',
    filename: 'Qwen3-1.7B-Q8_0.gguf',
    size_bytes: 1834426016,
    quant: 'Q8_0',
    blurb: 'Multilingual chat with good reasoning and coding for its size.',
  },
  {
    catalog_id: 'qwen3_4b_instruct_q8_0',
    name: 'Qwen3 4B',
    repo_id: 'Qwen/Qwen3-4B-GGUF',
    filename: 'Qwen3-4B-Q8_0.gguf',
    size_bytes: 4280404704,
    quant: 'Q8_0',
    blurb: 'Strong multilingual reasoning, math, and coding, with optional step-by-step thinking.',
  },
  {
    catalog_id: 'qwen3_8b_instruct_q8_0',
    name: 'Qwen3 8B',
    repo_id: 'Qwen/Qwen3-8B-GGUF',
    filename: 'Qwen3-8B-Q8_0.gguf',
    size_bytes: 8709518112,
    quant: 'Q8_0',
    blurb: 'Top-tier Qwen3 quality — strong reasoning, math, coding, and multilingual chat.',
  },
  {
    /* Must equal the /api/capabilities contract row id AND the backend catalog
       id (src/api/mod.rs) — `filename_is_supported_exact_row` joins catalog to
       row by EXACT id, and check-ledger-drift.mjs Check C fails a catalog entry
       with no contract row. The historical `gemma3_1b_it_q8_0` spelling matched
       neither and demoted this promoted row to Experimental. */
    catalog_id: 'gemma_3_1b_it_q8_0',
    name: 'Gemma 3 1B-It',
    repo_id: 'ggml-org/gemma-3-1b-it-GGUF',
    filename: 'gemma-3-1b-it-Q8_0.gguf',
    size_bytes: 1069306368,
    quant: 'Q8_0',
    blurb: 'A small Gemma for quick chat — runs on the Metal GPU-resident lane on Apple Silicon.',
  },
  {
    catalog_id: 'gemma4_e4b_it_q8_0',
    name: 'Gemma 4 E4B-It',
    repo_id: 'unsloth/gemma-4-E4B-it-GGUF',
    filename: 'gemma-4-E4B-it-Q8_0.gguf',
    size_bytes: 8192951456,
    quant: 'Q8_0',
    blurb: 'Google’s Gemma — capable multilingual chat and reasoning.',
  },
  {
    catalog_id: 'gemma4_e2b_it_q8_0',
    name: 'Gemma 4 E2B-It',
    repo_id: 'unsloth/gemma-4-E2B-it-GGUF',
    filename: 'gemma-4-E2B-it-Q8_0.gguf',
    size_bytes: 5048350848,
    quant: 'Q8_0',
    blurb: 'A compact Gemma model for multilingual chat.',
  },
  {
    catalog_id: 'gemma4_12b_it_q8_0',
    name: 'Gemma 4 12B-It (distributed)',
    repo_id: 'unsloth/gemma-4-12b-it-GGUF',
    filename: 'gemma-4-12b-it-Q8_0.gguf',
    size_bytes: 12669646240,
    quant: 'Q8_0',
    blurb: 'A larger Gemma for higher-quality multilingual chat and reasoning.',
  },
  {
    catalog_id: 'gemma4_26b_a4b_it_q4_0',
    name: 'Gemma 4 26B-A4B-It QAT (Ghost MoE)',
    repo_id: 'google/gemma-4-26B-A4B-it-qat-q4_0-gguf',
    filename: 'gemma-4-26B_q4_0-it.gguf',
    size_bytes: 14439361440,
    quant: 'Q4_0',
    blurb: 'A large mixture-of-experts Gemma, supported on Windows CUDA with the storage-backed Ghost MoE option.',
  },
  {
    /* The one Ornith artifact that is HF-pristine; its supported Q4_K_M/Q3_K_M
       siblings are in-house requants with no upstream file, so they stay
       download-free (NON_CATALOG_SUPPORTED_ARTIFACTS in src/api/mod.rs).

       The spaces in this id are deliberate and load-bearing — the ledger's
       bare-name row id must stay verbatim for the chat --agent gate. Note that
       check-ledger-drift.mjs Check C only parses `[a-z0-9_]+` ids, so this row is
       skipped there rather than validated; the Rust catalog is the surface that
       enforces the join. */
    catalog_id: 'Ornith 1.0 9B',
    name: 'Ornith 1.0 9B',
    repo_id: 'deepreinforce-ai/Ornith-1.0-9B-GGUF',
    filename: 'ornith-1.0-9b-Q8_0.gguf',
    size_bytes: 9527500992,
    quant: 'Q8_0',
    blurb: 'A large tool-capable model — the strongest agent lane, and a 9.5 GB download.',
  },
  {
    catalog_id: 'bonsai_4b_q1_0',
    name: 'Bonsai 4B Q1_0',
    repo_id: 'prism-ml/Bonsai-4B-gguf',
    filename: 'Bonsai-4B-Q1_0.gguf',
    size_bytes: 572270624,
    quant: 'Q1_0',
    blurb: 'Prism ML’s compact 1-bit Bonsai model, supported on Apple Silicon Metal and Windows CUDA.',
  },
  {
    catalog_id: 'ternary_bonsai_4b_q2_0',
    name: 'Ternary Bonsai 4B Q2_0',
    repo_id: 'prism-ml/Ternary-Bonsai-4B-gguf',
    filename: 'Ternary-Bonsai-4B-Q2_0.gguf',
    size_bytes: 1074969344,
    quant: 'Q2_0',
    blurb: 'The higher-quality ternary 4B pack, supported on Apple Silicon Metal and Windows CUDA.',
  },
  {
    catalog_id: 'ternary_bonsai_4b_pq2_0',
    name: 'Ternary Bonsai 4B PQ2_0',
    repo_id: 'prism-ml/Ternary-Bonsai-4B-gguf',
    filename: 'Ternary-Bonsai-4B-PQ2_0.gguf',
    size_bytes: 1074969344,
    quant: 'PQ2_0',
    blurb: 'The packed PQ2_0 variant of Ternary Bonsai 4B, supported on Apple Silicon Metal and Windows CUDA.',
  },
  {
    catalog_id: 'bonsai_8b_q1_0',
    name: 'Bonsai 8B Q1_0',
    repo_id: 'prism-ml/Bonsai-8B-gguf',
    filename: 'Bonsai-8B-Q1_0.gguf',
    size_bytes: 1158654496,
    quant: 'Q1_0',
    blurb: 'An 8B Bonsai model in a roughly 1.2 GB 1-bit pack, supported on Apple Silicon Metal and Windows CUDA.',
  },
  {
    catalog_id: 'ternary_bonsai_8b_q2_0',
    name: 'Ternary Bonsai 8B Q2_0',
    repo_id: 'prism-ml/Ternary-Bonsai-8B-gguf',
    filename: 'Ternary-Bonsai-8B-Q2_0.gguf',
    size_bytes: 2182184672,
    quant: 'Q2_0',
    blurb: 'The higher-quality ternary 8B pack, supported on Apple Silicon Metal and Windows CUDA.',
  },
  {
    catalog_id: 'bonsai_27b_q1_0',
    name: 'Bonsai 27B Q1_0',
    repo_id: 'prism-ml/Bonsai-27B-gguf',
    filename: 'Bonsai-27B-Q1_0.gguf',
    size_bytes: 3803452480,
    quant: 'Q1_0',
    companion_artifacts: [BONSAI_27B_VISION_PROJECTOR],
    blurb: 'The full 27B reasoning model for Metal and Windows CUDA; the Models download includes its vision projector.',
  },
  {
    catalog_id: 'ternary_bonsai_27b_q2_0',
    name: 'Ternary Bonsai 27B Q2_0',
    repo_id: 'prism-ml/Ternary-Bonsai-27B-gguf',
    filename: 'Ternary-Bonsai-27B-Q2_0.gguf',
    size_bytes: 7165121600,
    quant: 'Q2_0',
    companion_artifacts: [BONSAI_27B_VISION_PROJECTOR],
    blurb: 'The higher-quality 27B ternary pack for Metal and Windows CUDA; the Models download includes its vision projector.',
  },
  // Phase 2 exact-row expansion. The live compatibility contract distinguishes
  // verified-runnable rows from explicit load/parity/template holds and from the
  // narrower Supported tier.
  { catalog_id: 'lfm2_5_1_2b_instruct_q8_0', name: 'LFM2.5 1.2B Instruct', repo_id: 'LiquidAI/LFM2.5-1.2B-Instruct-GGUF', filename: 'LFM2.5-1.2B-Instruct-Q8_0.gguf', size_bytes: 1246253888, quant: 'Q8_0', blurb: 'Compact Liquid AI instruct model; exact row verified for load, short greedy output, API, and UI.' },
  { catalog_id: 'lfm2_5_1_2b_thinking_q8_0', name: 'LFM2.5 1.2B Thinking', repo_id: 'LiquidAI/LFM2.5-1.2B-Thinking-GGUF', filename: 'LFM2.5-1.2B-Thinking-Q8_0.gguf', size_bytes: 1246254080, quant: 'Q8_0', blurb: 'Compact reasoning-tuned Liquid AI model; currently held on parity.' },
  { catalog_id: 'gemma3_270m_it_q8_0', name: 'Gemma 3 270M-It', repo_id: 'unsloth/gemma-3-270m-it-GGUF', filename: 'gemma-3-270m-it-Q8_0.gguf', size_bytes: 291546144, quant: 'Q8_0', blurb: 'Tiny Gemma instruct model; exact row verified for load, short greedy output, API, and UI.' },
  { catalog_id: 'gemma3_4b_it_q8_0', name: 'Gemma 3 4B-It', repo_id: 'ggml-org/gemma-3-4b-it-GGUF', filename: 'gemma-3-4b-it-Q8_0.gguf', size_bytes: 4130226336, quant: 'Q8_0', blurb: 'Capable Gemma text model; tokenizer and template pass, but greedy output diverges at token 3.' },
  { catalog_id: 'llama3_1_8b_instruct_q8_0', name: 'Llama 3.1 8B Instruct', repo_id: 'bartowski/Meta-Llama-3.1-8B-Instruct-GGUF', filename: 'Meta-Llama-3.1-8B-Instruct-Q8_0.gguf', size_bytes: 8540775840, quant: 'Q8_0', blurb: 'General-purpose Llama 3.1 instruct row; currently held on parity.' },
  { catalog_id: 'mistral_7b_instruct_v0_2_q8_0', name: 'Mistral 7B Instruct v0.2', repo_id: 'TheBloke/Mistral-7B-Instruct-v0.2-GGUF', filename: 'mistral-7b-instruct-v0.2.Q8_0.gguf', size_bytes: 7695857952, quant: 'Q8_0', blurb: 'Classic Mistral instruct row; exact row verified for load, short greedy output, API, and UI.' },
  { catalog_id: 'qwen2_5_0_5b_instruct_q8_0', name: 'Qwen2.5 0.5B Instruct', repo_id: 'Qwen/Qwen2.5-0.5B-Instruct-GGUF', filename: 'qwen2.5-0.5b-instruct-q8_0.gguf', size_bytes: 675710816, quant: 'Q8_0', blurb: 'Very small multilingual Qwen row; currently held on one parity frontier.' },
  { catalog_id: 'qwen2_5_1_5b_instruct_q8_0', name: 'Qwen2.5 1.5B Instruct', repo_id: 'Qwen/Qwen2.5-1.5B-Instruct-GGUF', filename: 'qwen2.5-1.5b-instruct-q8_0.gguf', size_bytes: 1894532128, quant: 'Q8_0', blurb: 'Compact multilingual Qwen instruct row; currently held on parity.' },
  { catalog_id: 'qwen2_5_coder_1_5b_instruct_q8_0', name: 'Qwen2.5 Coder 1.5B Instruct', repo_id: 'Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF', filename: 'qwen2.5-coder-1.5b-instruct-q8_0.gguf', size_bytes: 1894532160, quant: 'Q8_0', blurb: 'Compact code-focused Qwen row; exact row verified for load, short greedy output, API, and UI.' },
  { catalog_id: 'qwen3_5_0_8b_q8_0', name: 'Qwen3.5 0.8B', repo_id: 'unsloth/Qwen3.5-0.8B-GGUF', filename: 'Qwen3.5-0.8B-Q8_0.gguf', size_bytes: 811843840, quant: 'Q8_0', blurb: 'Small hybrid Qwen3.5 row; exact row verified for load, short greedy output, API, and UI.' },
  { catalog_id: 'qwen3_5_2b_q8_0', name: 'Qwen3.5 2B', repo_id: 'unsloth/Qwen3.5-2B-GGUF', filename: 'Qwen3.5-2B-Q8_0.gguf', size_bytes: 2012012800, quant: 'Q8_0', blurb: 'Compact hybrid Qwen3.5 row; exact row verified for load, short greedy output, API, and UI.' },
  { catalog_id: 'qwen3_5_4b_q8_0', name: 'Qwen3.5 4B', repo_id: 'unsloth/Qwen3.5-4B-GGUF', filename: 'Qwen3.5-4B-Q8_0.gguf', size_bytes: 4482403488, quant: 'Q8_0', blurb: 'Mid-size hybrid Qwen3.5 row; currently held on parity.' },
  { catalog_id: 'qwen3_5_9b_q8_0', name: 'Qwen3.5 9B', repo_id: 'unsloth/Qwen3.5-9B-GGUF', filename: 'Qwen3.5-9B-Q8_0.gguf', size_bytes: 9527502048, quant: 'Q8_0', blurb: 'Large hybrid Qwen3.5 row; currently held on parity.' },
  { catalog_id: 'deepseek_r1_distill_qwen_1_5b_q8_0', name: 'DeepSeek R1 Distill Qwen 1.5B', repo_id: 'unsloth/DeepSeek-R1-Distill-Qwen-1.5B-GGUF', filename: 'DeepSeek-R1-Distill-Qwen-1.5B-Q8_0.gguf', size_bytes: 1894532416, quant: 'Q8_0', blurb: 'Small DeepSeek reasoning distill; currently held on parity.' },
  { catalog_id: 'deepseek_r1_distill_llama_8b_q8_0', name: 'DeepSeek R1 Distill Llama 8B', repo_id: 'unsloth/DeepSeek-R1-Distill-Llama-8B-GGUF', filename: 'DeepSeek-R1-Distill-Llama-8B-Q8_0.gguf', size_bytes: 8540773088, quant: 'Q8_0', blurb: 'Llama-based DeepSeek reasoning distill; exact row verified for load, short greedy output, API, and UI.' },
  { catalog_id: 'phi3_mini_4k_instruct_q8_0', name: 'Phi-3 Mini 4K Instruct', repo_id: 'bartowski/Phi-3-mini-4k-instruct-GGUF', filename: 'Phi-3-mini-4k-instruct-Q8_0.gguf', size_bytes: 4061221376, quant: 'Q8_0', blurb: 'Compact Microsoft Phi-3 row; supported for the exact certified Q8_0 artifact on Windows x86_64.' },
  { catalog_id: 'phi4_mini_instruct_q8_0', name: 'Phi-4 Mini Instruct', repo_id: 'unsloth/Phi-4-mini-instruct-GGUF', filename: 'Phi-4-mini-instruct.Q8_0.gguf', size_bytes: 4084611040, quant: 'Q8_0', blurb: 'Microsoft Phi-4 Mini row; currently held on tensor binding.' },
  { catalog_id: 'gemma2_9b_it_q8_0', name: 'Gemma 2 9B-It', repo_id: 'BenevolenceMessiah/gemma-2-9b-it-Q8_0-GGUF', filename: 'gemma-2-9b-it-q8_0.gguf', size_bytes: 9827149312, quant: 'Q8_0', blurb: 'Large Gemma 2 instruct row; exact row verified for load, short greedy output, API, and UI.' },
  { catalog_id: 'smollm3_3b_q8_0', name: 'SmolLM3 3B', repo_id: 'ggml-org/SmolLM3-3B-GGUF', filename: 'SmolLM3-Q8_0.gguf', size_bytes: 3275574624, quant: 'Q8_0', blurb: 'Compact SmolLM3 row; raw parity passes while the chat envelope stays bounded.' },
  { catalog_id: 'aya_expanse_8b_q4_k_m', name: 'Aya Expanse 8B', repo_id: 'bartowski/aya-expanse-8b-GGUF', filename: 'aya-expanse-8b-Q4_K_M.gguf', size_bytes: 5056982720, quant: 'Q4_K_M', blurb: 'Multilingual Command-R row under a non-commercial license; currently held on parity.' },
]
